server:
  port: 80
management:
  endpoints:
    web:
      exposure:
        include: "*" #开放所有的路径
      base-path: /actuator # 监控服务父路径
  endpoint:
    health:
      show-details: always # 总是显示信息
      show-components: always # 总是显示组件信息