mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
  type-aliases-package: com.yzb.oauth.vo

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis-review?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: accp
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid: #定义数据库连接池所需要到相关配置项
      initial-size: 1 # 初始连接池大小
      min-idle: 10 #最小维持到连接池大小
      max-active: 50 #最大可提供的连接数量
      max-wait: 2000 #最长到等待时间
      time-between-eviction-runs-millis: 6000 #关闭空闲连接的间隔（毫秒）
      min-evictable-idle-time-millis: 3000 #连接到最小生存时间
      validation-query: select 1 from dual #验证查询，数据库的状态检测
      test-while-idle: true # 测试连接是否可用
      test-on-borrow: false #在获得连接之前是否要进行测试
      test-on-return: false #在返回之前是否要进行测试
  redis:
    host: 192.168.230.160
    port: 6379
#    password: hello
    database: 0 # 默认就是0m
    timeout: 200ms
    lettuce:
      pool:
        max-active: 100 # 最大连接数
        max-idle: 20 # 最大空闲维持数
        min-idle: 10
        time-between-eviction-runs: 2000 #每2秒回收一次


